-
  name: 'SubRoutes'
  uriPattern: '<SubRoutes>'
  defaults:
    '@package': 'SteinbauerIT.MicrosoftEntraIdAuthentication'
    '@format': 'html'
  subRoutes:
    'SubRoutes':
      package: 'SteinbauerIT.MicrosoftEntraIdAuthentication'
      suffix:  'Main'
